### ISSUE TITLE
property ' ashift' is not a valid pool property

### ISSUE THREAD

**Issue by DonSYS91** [terem42/zfs-hetzner-vm#21] opened 2021-11-25 18:28 UTC
Hello, 
the Debian 11 script is erroring out on the stage: ======= create zfs pools and datasets ==========
with the error: "property ' ashift' is not a valid pool property"

**Comment by terem42** [comment] 2021-11-25 22:40
Thanks for the feedback, the error was caused by excessive double quoting. Fixed now for all scripts.

**Closed by terem42** 2021-11-25 22:40 UTC
